name: posyandu_web_crud
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  crypto: ^3.0.6
  intl: ^0.20.2
  google_fonts: ^6.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^1.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/posyandu_logo.png
